---
dataSources:
  - kind: substrate/Runtime
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - filter:
            method: Deposit
            module: balances
          handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
    name: main
    startBlock: 8000000
description: ''
network:
  endpoint: wss://crab-rpc.darwinia.network/
  types:
    AccountInfo:
      nonce: Index
      refcount: RefCount
      data: AccountData
    AccountSigner: MultiSigner
    Address: MultiAddress
    AncestryProof: ()
    Announcement: ProxyAnnouncement
    AuthorityId: '[u8;32]'
    AuthoritySet:
      authorities: AuthorityList
      set_id: SetId
    AuthoritySignature: '[u8;64]'
    BSCHeader:
      parentHash: H256
      uncleHash: H256
      coinbase: EthereumAddress
      stateRoot: H256
      transactionsRoot: H256
      receiptsRoot: H256
      logBloom: Bloom
      difficulty: U256
      number: u64
      gasLimit: U256
      gasUsed: U256
      timestamp: u64
      extraData: Bytes
      mixDigest: H256
      nonce: Bytes
    BabeEpochConfiguration: 'Null'
    BlockNumberFor: BlockNumber
    BridgedBlockHash: MillauBlockHash
    BridgedBlockNumber: MillauBlockNumber
    BridgedHeader: MillauHeader
    BridgedOpaqueCall: Vec<u8>
    CallOrigin:
      _enum:
        SourceRoot: ()
        TargetAccount: (SourceAccountId, MultiSigner, MultiSignature)
        SourceAccount: SourceAccountId
    ChainId: Id
    ChainProperties:
      ss58Format: Option<u8>
      tokenDecimals: Option<Vec<u32>>
      tokenSymbol: Option<Vec<Text>>
    Commit:
      target_hash: BridgedBlockHash
      target_number: BridgedBlockNumber
      precommits: Vec<SignedPrecommit>
    CompactAssignments: CompactAssignmentsWith16
    EcdsaAddress: EthereumAddress
    ElectionCompute:
      _enum:
        - OnChain
        - Signed
        - Authority
    ElectionResultT:
      electedStashes: Vec<AccountId>
      exposures: Vec<(AccountId, ExposureT)>
      compute: ElectionCompute
    Exposure: ExposureT
    Fee: MillauBalance
    GrandpaJustification:
      round: u64
      commit: Commit
      votes_ancestries: Vec<BridgedHeader>
    Id: '[u8; 4]'
    ImportedHeader:
      header: BridgedHeader
      requires_justification: bool
      is_finalized: bool
      signal_hash: Option<BridgedBlockHash>
    InboundLaneData:
      relayers: Vec<(MessageNonce, MessageNonce, RelayerId)>
      last_confirmed_nonce: MessageNonce
    InboundRelayer: AccountId
    InitializationData:
      authority_list: AuthorityList
      header: Header
      is_halted: bool
      set_id: SetId
    LaneId: Id
    LogEntry: '{}'
    LookupSource: MultiAddress
    MMRProofResult:
      mmrSize: u64
      proof: Text
    MessageData:
      payload: MessagePayload
      fee: Fee
    MessageFeeData:
      lane_id: LaneId
      payload: OutboundPayload
    MessageId: (Id, MessageNonce)
    MessageKey:
      laneId: LaneId
      nonce: MessageNonce
    MessageNonce: u64
    MessagePayload: Vec<u8>
    MessagesDeliveryProofOf:
      bridged_header_hash: BridgedBlockHash
      storage_proof: Vec<StorageProofItem>
      lane: LaneId
    MessagesProofOf:
      bridged_header_hash: BridgedBlockHash
      storage_proof: Vec<StorageProofItem>
      lane: LaneId
      nonces_start: MessageNonce
      nonces_end: MessageNonce
    MillauBalance: u64
    MillauBlockHash: H512
    MillauBlockNumber: u64
    MillauDigest:
      logs: Vec<MillauDigestItem>
    MillauDigestItem:
      _enum:
        Other: Vec<u8>
        AuthoritiesChange: Vec<AuthorityId>
        ChangesTrieRoot: MillauBlockHash
        SealV0: SealV0
        Consensus: Consensus
        Seal: Seal
        PreRuntime: PreRuntime
    MillauHeader:
      parent_Hash: MillauBlockHash
      number: Compact<MillauBlockNumber>
      state_root: MillauBlockHash
      extrinsics_root: MillauBlockHash
      digest: MillauDigest
    MmrNodesPruningConfiguration:
      step: NodeIndex
      progress: NodeIndex
      lastPosition: NodeIndex
    MultiAddress: GenericMultiAddress
    MultiSigner:
      _enum:
        Ed25519: H256
        Sr25519: H256
        Ecdsa: '[u8;33]'
    OutboundLaneData:
      latest_generated_nonce: MessageNonce
      latest_received_nonce: MessageNonce
      oldest_unpruned_nonce: MessageNonce
    OutboundMessageFee: Fee
    OutboundPayload:
      spec_version: SpecVersion
      weight: Weight
      origin: CallOrigin
      call: BridgedOpaqueCall
    PalletId: LockIdentifier
    Parameter:
      _enum:
        MillauToRialtoConversionRate: u128
    PowerOf:
      power: Power
    Precommit:
      target_hash: BridgedBlockHash
      target_number: BridgedBlockNumber
    ProxyAnnouncement:
      real: AccountId
      callHash: Hash
      height: BlockNumber
    ProxyDefinition:
      delegate: AccountId
      proxyType: ProxyType
      delay: BlockNumber
    RawSolution: RawSolutionWith16
    Reasons:
      _enum:
        - Fee
        - Misc
        - All
    RelayerId: AccountId
    SignedPrecommit:
      precommit: Precommit
      signature: AuthoritySignature
      id: AuthorityId
    Signer: EthereumAddress
    SourceAccountId: AccountId
    SpecVersion: u32
    Status:
      _enum:
        Free: 'Null'
        Reserved: 'Null'
    StorageProofItem: Vec<u8>
    TransactionOutcome: '{}'
    TreasuryProposal:
      proposer: AccountId
      beneficiary: AccountId
      ringValue: Balance
      ringBond: Balance
      ktonValue: Balance
      ktonBond: Balance
    TronAddress: EthereumAddress
    UnrewardedRelayersState:
      unrewarded_relayer_entries: MessageNonce
      messages_in_oldest_entry: MessageNonce
      total_messages: MessageNonce
    UsableBalance:
      usableBalance: Balance
    ValidatorPrefs: ValidatorPrefsWithBlocked
    # types below are consist with https://github.com/darwinia-network/darwinia/blob/master/runtime/crab/types.json
    #__[pallet.balances]__: {}
    BalanceInfo: 'Null'
    BalanceLock:
      id: LockIdentifier
      lockFor: LockFor
      lockReasons: LockReasons
    LockFor:
      _enum:
        Common: Common
        Staking: StakingLock
    Common:
      amount: Balance
    StakingLock:
      stakingAmount: Balance
      unbondings: Vec<Unbonding>
    LockReasons:
      _enum:
        Fee: 'Null'
        Misc: 'Null'
        All: 'Null'
    Unbonding:
      amount: Balance
      until: BlockNumber
    AccountData:
      free: Balance
      reserved: Balance
      freeKton: Balance
      reservedKton: Balance
    # __[pallet.staking]__: {}
    RingBalance: Balance
    KtonBalance: Balance
    TsInMs: u64
    Power: u32
    DepositId: U256
    StakingBalanceT:
      _enum:
        RingBalance: Balance
        KtonBalance: Balance
    StakingLedgerT:
      stash: AccountId
      activeRing: Compact<Balance>
      activeDepositRing: Compact<Balance>
      activeKton: Compact<Balance>
      depositItems: Vec<TimeDepositItem>
      ringStakingLock: StakingLock
      ktonStakingLock: StakingLock
      claimedRewards: Vec<EraIndex>
    TimeDepositItem:
      value: Compact<Balance>
      startTime: Compact<TsInMs>
      expireTime: Compact<TsInMs>
    ExposureT:
      ownRingBalance: Compact<Balance>
      ownKtonBalance: Compact<Balance>
      ownPower: Power
      totalPower: Power
      others: Vec<IndividualExposure>
    IndividualExposure:
      who: AccountId
      ringBalance: Compact<Balance>
      ktonBalance: Compact<Balance>
      power: Power
    RKT:
      r: Balance
      k: Balance
    SpanRecord:
      slashed: RKT
      paidOut: RKT
    UnappliedSlash:
      validator: AccountId
      own: RKT
      others: Vec<(AccountId, RKT)>
      reporters: Vec<AccountId>
      payout: RKT
    # __[pallet.bridge.crab]__: {}
    MappedRing: u128
    #__[pallet.bridge.eth]__: {}
    EthereumTransactionIndex: '(H256, u64)'
    EthereumBlockNumber: u64
    EthereumHeader:
      parentHash: H256
      timestamp: u64
      number: EthereumBlockNumber
      author: EthereumAddress
      transactionsRoot: H256
      unclesHash: H256
      extraData: Bytes
      stateRoot: H256
      receiptsRoot: H256
      logBloom: Bloom
      gasUsed: U256
      gasLimit: U256
      difficulty: U256
      seal: Vec<Bytes>
      baseFeePerGas: Option<U256>
      hash: Option<H256>
    EthereumAddress: H160
    EcdsaMessage: '[u8; 32; EcdsaMessage]'
    Bloom: '[u8; 256; Bloom]'
    H128: '[u8; 16; H128]'
    EthashProof:
      dagNodes: '(H512, H512)'
      proof: Vec<H128>
    EthereumReceipt:
      Legacy: LegacyReceipt
      AccessList: LegacyReceipt
      EIP1559Transaction: LegacyReceipt
    LegacyReceipt:
      gas_used: U256
      log_bloom: Bloom
      logs: Vec<LogEntry>
      outcome: TransactionOutcome
    EthereumNetwork:
      _enum:
        Mainnet:
        Ropsten:
    RedeemFor:
      _enum:
        Token:
        Deposit:
    EthereumReceiptProof:
      index: u64
      proof: Bytes
      header_hash: H256
    EthereumReceiptProofThing: '(EthereumHeader, EthereumReceiptProof, MMRProof)'
    MMRProof:
      member_leaf_index: u64
      last_leaf_index: u64
      proof: Vec<H256>
    EthereumRelayHeaderParcel:
      header: EthereumHeader
      parent_mmr_root: H256
    EthereumRelayProofs:
      ethash_proof: Vec<EthashProof>
      mmr_proof: Vec<H256>
    # __[TODO.Generalize]__: ''
    RelayAuthoritySigner: EthereumAddress
    RelayAuthorityMessage: EcdsaMessage
    RelayAuthoritySignature: EcdsaSignature
    # __[pallet.claims]__: {}
    OtherSignature:
      _enum:
        Eth: EcdsaSignature
        Tron: EcdsaSignature
    EcdsaSignature: '[u8; 65; EcdsaSignature]'
    OtherAddress:
      _enum:
        Eth: '[u8; 20; EthereumAddress]'
        Tron: '[u8; 20; TronAddress]'
    AddressT: '[u8; 20; AddressT]'
    # __[pallet.fee_market]__:
    Relayer:
      id: AccountId
      collateral: Balance
      fee: Balance
    Order:
      lane: LaneId
      message: MessageNonce
      sentTime: BlockNumber
      confirmTime: BlockNumber
      lockedCollateral: Balance
      assignedRelayers: Vec<PriorRelayer>
    PriorRelayer:
      id: AccountId
      fee: Balance
      valid_range: BlockNumber
    # __[pallet.header-mmr]__: {}
    NodeIndex: u64
    MerkleMountainRangeRootLog:
      prefix: '[u8; 4; Prefix]'
      parentMmrRoot: Hash
    # __[primitives.relay]__: {}
    OpCode: '[u8; 4; OpCode]'
    Term: u32
    RelayHeaderId: EthereumBlockNumber
    RelayHeaderParcel: EthereumRelayHeaderParcel
    RelayProofs: EthereumRelayProofs
    RelayAffirmationId:
      game_id: EthereumBlockNumber
      round: u32
      index: u32
    RelayAffirmationT:
      relayer: AccountId
      relayHeaderParcels: EthereumRelayHeaderParcel
      bond: Balance
      maybeExtendedRelayAffirmationId: Option<RelayAffirmationId>
      verified: bool
    RelayVotingState:
      ayes: Vec<AccountId>
      nays: Vec<AccountId>
    RelayAuthorityT:
      accountId: AccountId
      signer: Signer
      stake: Balance
      term: BlockNumber
    ScheduledAuthoritiesChangeT:
      nextAuthorities: Vec<RelayAuthorityT>
      deadline: BlockNumber
    MmrRootToSign:
      mmrRoot: Hash
      signatures: Vec<(AccountId, EcdsaSignature)>
    MMRRoot: Hash
    # __[crab.runtime]__: {}
    ProxyType:
      _enum:
        Any: 'Null'
        NonTransfer: 'Null'
        Governance: 'Null'
        Staking: 'Null'
        IdentityJudgement: 'Null'
        EthereumBridge: 'Null'
    # __[node.rpc]__: {}
    BalancesRuntimeDispatchInfo:
      usable_balance: Balance
    StakingRuntimeDispatchInfo:
      power: Power
    InProcessOrders:
      orders: Vec<LaneId, MessageNonce>
  typesBundle:
    spec:
      Darwinia:
        types:
          - minmax:
              - 42
              - 43
            types:
              AccountInfo: AccountInfoWithTripleRefCount
              AccountInfoWithTripleRefCount:
                consumers: RefCount
                data: AccountData
                nonce: Index
                providers: RefCount
            AccountData:
              feeFrozen: Balance
              free: Balance
              reserved: Balance
              freeKton: Balance
              reservedKton: Balance
              miscFrozen: Balance
            BalanceInfo: '{}'
            BalanceLock:
              id: LockIdentifier
              lockFor: LockFor
              reasons: Reasons
            EcdsaMessage: H256
            MmrRootToSign:
              mmrRoot: Hash
              signatures: Vec<(EthereumAddress, EcdsaSignature)>
            OtherAddress:
              _enum:
                Eth: EthereumAddress
                Tron: TronAddress
            RelayAffirmationId:
              relayHeaderId: EthereumBlockNumber
              round: u32
              index: u32
            RelayAuthoritySigner: EcdsaAddress
            RelayAuthorityT:
              accountId: AccountId
              signer: EthereumAddress
              stake: Balance
              term: BlockNumber
            Term: BlockNumber
            Unbonding:
              amount: Balance
              moment: BlockNumber
          - minmax:
              - 43
              - 1150
            types:
              AccountInfo: AccountInfoWithTripleRefCount
              AccountInfoWithTripleRefCount:
                consumers: RefCount
                data: AccountData
                nonce: Index
                providers: RefCount
                sufficients: RefCount
              AccountData:
                feeFrozen: Balance
                free: Balance
                reserved: Balance
                freeKton: Balance
                reservedKton: Balance
                miscFrozen: Balance
              BalanceInfo: '{}'
              BalanceLock:
                id: LockIdentifier
                lockFor: LockFor
                reasons: Reasons
              EcdsaMessage: H256
              MmrRootToSign:
                mmrRoot: Hash
                signatures: Vec<(EthereumAddress, EcdsaSignature)>
              OtherAddress:
                _enum:
                  Eth: EthereumAddress
                  Tron: TronAddress
              RelayAffirmationId:
                relayHeaderId: EthereumBlockNumber
                round: u32
                index: u32
              RelayAuthoritySigner: EcdsaAddress
              RelayAuthorityT:
                accountId: AccountId
                signer: EthereumAddress
                stake: Balance
                term: BlockNumber
              Term: BlockNumber
              Unbonding:
                amount: Balance
                moment: BlockNumber
          - minmax:
              - 1150
            types:
              AccountInfo: AccountInfoWithTripleRefCount
              AccountInfoWithTripleRefCount:
                consumers: RefCount
                data: AccountData
                nonce: Index
                providers: RefCount
                sufficients: RefCount

repository: ''
schema: ./schema.graphql
specVersion: 0.0.1